version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Frontend:/app

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - MongoDBURI=mongodb://mongodb:27017/React-foodorder
    volumes:
      - ./Backend:/app
    depends_on:
      - mongodb

volumes:
  mongo-data:
